# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcT0sim <- function(CvSqrt, powV, nperm) {
    .Call('GMaSPU_calcT0sim', PACKAGE = 'GMaSPU', CvSqrt, powV, nperm)
}

set_seed <- function(seed) {
    invisible(.Call('GMaSPU_set_seed', PACKAGE = 'GMaSPU', seed))
}

avg_rank <- function(x) {
    .Call('GMaSPU_avg_rank', PACKAGE = 'GMaSPU', x)
}

aSPUsPathEngine2 <- function(CH, CHcovSq, pow1, pow2, nGenes, n_perm, k, nSNPs0, nChrom0, Ts2, s) {
    .Call('GMaSPU_aSPUsPathEngine2', PACKAGE = 'GMaSPU', CH, CHcovSq, pow1, pow2, nGenes, n_perm, k, nSNPs0, nChrom0, Ts2, s)
}

